## importing

In [7]:
#basic packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#sklearn models
from sklearn.linear_model import RidgeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split

#encoder
from sklearn.preprocessing import LabelEncoder

#metrics
from sklearn import metrics

#tensorflow
import tensorflow as tf

#random
import random
from datetime import datetime

## data processing

In [2]:
data = pd.read_csv('/Users/jlisd/Downloads/MLProject/iris.data', names = ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)', 'class'])
#data.head()

In [22]:
X = data[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']].values
#X.head()

In [23]:
Y_raw = data[['class']].values
#Y.head()

In [24]:
encoder =  LabelEncoder()
Y1 = encoder.fit_transform(Y_raw)
#print(Y1)

C:\Users\jlisd\Anaconda3\lib\site-packages\sklearn\preprocessing\_label.py:251: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [29]:
Y = pd.get_dummies(Y1).values

In [30]:
print(X[0:5])
print(Y[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


## creating the random state

In [31]:
random_state = random.seed(datetime.now())
test_size = 0.5

In [32]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = test_size, random_state = random_state)
#print("data size: " + str(len(X.index)))
#print("training size: " + str(len(X_train.index)))
#print("test size: " + str(len(X_test.index)))

In [33]:
X_train

array([[6.8, 3.2, 5.9, 2.3],
       [6.3, 3.3, 4.7, 1.6],
       [6.6, 2.9, 4.6, 1.3],
       [4.9, 3.1, 1.5, 0.1],
       [4.7, 3.2, 1.6, 0.2],
       [5.3, 3.7, 1.5, 0.2],
       [5.4, 3.9, 1.3, 0.4],
       [5.6, 3. , 4.1, 1.3],
       [6.9, 3.2, 5.7, 2.3],
       [6. , 2.7, 5.1, 1.6],
       [5.6, 3. , 4.5, 1.5],
       [5.5, 3.5, 1.3, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5. , 3.4, 1.6, 0.4],
       [6.7, 3.1, 4.7, 1.5],
       [6.5, 2.8, 4.6, 1.5],
       [6. , 2.2, 4. , 1. ],
       [5.2, 2.7, 3.9, 1.4],
       [7.9, 3.8, 6.4, 2. ],
       [5.7, 2.5, 5. , 2. ],
       [5. , 3.6, 1.4, 0.2],
       [5.6, 2.8, 4.9, 2. ],
       [6.5, 3. , 5.2, 2. ],
       [6.7, 3.1, 4.4, 1.4],
       [5. , 3.4, 1.5, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.4, 2.9, 1.4, 0.2],
       [5.7, 2.8, 4.5, 1.3],
       [6.8, 2.8, 4.8, 1.4],
       [7.7, 3.8, 6.7, 2.2],
       [6.1, 2.8, 4. , 1.3],
       [6.7, 3.1, 5.6, 2.4],
       [5.5, 2.3, 4. , 1.3],
       [6.5, 3.2, 5.1, 2. ],
       [5.2, 4

 ## model building

In [23]:
knn = KNeighborsClassifier()
knn.fit(X_train, Y_train.values.ravel())
knn_prediction = knn.predict(X_test)
print("K Nearest Neighbors model accuracy: " + str(metrics.accuracy_score(knn_prediction, Y_test)))

K Nearest Neighbors model accuracy: 0.9733333333333334


In [24]:
ridge = RidgeClassifier()
ridge.fit(X_train, Y_train.values.ravel())
ridge_prediction = ridge.predict(X_test)
print("Ridge model accuracy: " + str(metrics.accuracy_score(ridge_prediction, Y_test)))

Ridge model accuracy: 0.8666666666666667


In [25]:
dt = DecisionTreeClassifier(max_depth = 3, random_state = random_state)
dt.fit(X_train, Y_train)
dt_prediction = dt.predict(X_test)
print("Decision tree model accuracy: " + str(metrics.accuracy_score(dt_prediction, Y_test)))

Decision tree model accuracy: 0.8933333333333333


In [26]:
rf = RandomForestClassifier()
rf.fit(X_train, Y_train)
rf_prediction = dt.predict(X_test)
print("Decision tree model accuracy: " + str(metrics.accuracy_score(rf_prediction, Y_test)))

Decision tree model accuracy: 0.8933333333333333


C:\Users\jlisd\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  


## tensorflow model

In [37]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model.summary()

ValueError: This model has not yet been built. Build the model first by calling `build()` or calling `fit()` with some data, or specify an `input_shape` argument in the first layer(s) for automatic build.

In [27]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])

In [34]:
model.fit(X_train, Y_train, batch_size=50, epochs=100)

Epoch 1/100
75/75 [==============================] - 0s 3ms/sample - loss: 2.0995 - acc: 0.3200
Epoch 2/100
75/75 [==============================] - 0s 79us/sample - loss: 1.9338 - acc: 0.3200
Epoch 3/100
75/75 [==============================] - 0s 66us/sample - loss: 1.8307 - acc: 0.3200
Epoch 4/100
75/75 [==============================] - 0s 80us/sample - loss: 1.7444 - acc: 0.3200
Epoch 5/100
75/75 [==============================] - 0s 133us/sample - loss: 1.6758 - acc: 0.1467
Epoch 6/100
75/75 [==============================] - 0s 120us/sample - loss: 1.6217 - acc: 0.0800
Epoch 7/100
75/75 [==============================] - 0s 106us/sample - loss: 1.5755 - acc: 0.0267
Epoch 8/100
75/75 [==============================] - 0s 93us/sample - loss: 1.5329 - acc: 0.0267
Epoch 9/100
75/75 [==============================] - 0s 106us/sample - loss: 1.4930 - acc: 0.0400
Epoch 10/100
75/75 [==============================] - 0s 120us/sample - loss: 1.4529 - acc: 0.0267
Epoch 11/100
75/75 [=====

75/75 [==============================] - 0s 93us/sample - loss: 0.6440 - acc: 0.9333
Epoch 85/100
75/75 [==============================] - 0s 93us/sample - loss: 0.6401 - acc: 0.9333
Epoch 86/100
75/75 [==============================] - 0s 66us/sample - loss: 0.6335 - acc: 0.8933
Epoch 87/100
75/75 [==============================] - 0s 120us/sample - loss: 0.6291 - acc: 0.8933
Epoch 88/100
75/75 [==============================] - 0s 80us/sample - loss: 0.6230 - acc: 0.9733
Epoch 89/100
75/75 [==============================] - 0s 80us/sample - loss: 0.6193 - acc: 0.9467
Epoch 90/100
75/75 [==============================] - 0s 120us/sample - loss: 0.6127 - acc: 0.8933
Epoch 91/100
75/75 [==============================] - 0s 106us/sample - loss: 0.6085 - acc: 0.9333
Epoch 92/100
75/75 [==============================] - 0s 93us/sample - loss: 0.6047 - acc: 0.9600
Epoch 93/100
75/75 [==============================] - 0s 93us/sample - loss: 0.5992 - acc: 0.9867
Epoch 94/100
75/75 [==========

In [35]:
loss, accuracy = model.evaluate(X_test, Y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.5593370779355367
Test accuracy: 0.96
